name: armazen
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  equatable: 2.0.3
  http: 0.13.3
  flutter_secure_storage: 4.2.1
  localstorage: 4.0.0+1

flutter:
  uses-material-design: true
